IMPORTING THE LIBRARIES

In [13]:
import numpy as np
import tensorflow as tf
import pandas as pd

IMPORTING THE DATASET

In [14]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:,3:-1].values 
y = dataset.iloc[:,-1].values
#print(x)
#print(y)

LABEL ENCODING THE CATEGORICAL VARIABLE --> MALE / FEMALE

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])


ONE HOT ENCODING THE GEOGRAPHY COLUMN

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


SPLITTING THE DATASET INTO TRAINGING AND TESTING SET

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=0)

FEATURE SCALING

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test) 

BUILDING AN ANN

In [19]:
#initializing the ANN
ann = tf.keras.models.Sequential()
#adding the first input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=7, activation='relu'))
#adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=7, activation='relu'))
#adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

TRAINING THE ANN

In [20]:
#compiling the ANN
ann.compile(optimizer='adam',loss='binary_crossentropy' ,metrics=['accuracy'])
#training ANN on the training set
ann.fit(x_train,y_train,batch_size=32,epochs=100)


Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5195 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4620 - accuracy: 0.7969
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4405 - accuracy: 0.8031
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4304 - accuracy: 0.8130
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4232 - accuracy: 0.8202
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4177 - accuracy: 0.8251
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4125 - accuracy: 0.8251
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4085 - accuracy: 0.8276
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4046 - accuracy: 0.8281
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4015 - accura

PREDICTING A SINGLE VALUE

In [21]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

1/1 [==============================] - 0s 76ms/step
[[False]]


PREDICTING THE TEST RESULTS

In [22]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


CONFUSION MATRIX

In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1491  104]
 [ 170  235]]


0.863